### PR TITLE
feat(ids): Add Support For Pre-Alarm State

### PR DESCRIPTION
**Pull request by JarFiles**
See: https://github.com/BoschSmartHome/bosch-shc-api-docs/blob/4f6ecf0fadd3d3e855d81f7f413891c9fd07a3bd/openapi/IntrusionDetectionSystem-local-openapi-v3.yml#L171

### CODE REVIEW

**Comment by JarFiles** [comment]
Would be great if this could be merged so I can implement the pending alarm state in home assistant.

**Review by tschamm — APPROVED** [review]
LGTM

**Comment by tschamm** [comment]
Thank you!
I’m in holiday right now, let me see how I can push it to pypi.

**Comment by tschamm** [comment]
Version 0.2.92 is now uploaded to pypi.org

**Pull request merged**
