### PR TITLE
Adding support for the "Micromodule Dimmer"

### PR DESCRIPTION
**Pull request by jumlu**
I added some code so the Micromodule Dimmer is supported in a first version. Some functionality is not working yet (DimmerConfiguration), but at least you can read and write the most important things (brightness, on-off). I might add further functionality later.

### CODE REVIEW

**Review by tschamm — APPROVED** [review]
LGTM

**Comment by tschamm** [comment]
Thank you!

**Comment by jumlu** [comment]
Hi @tschamm, the integration to HASS works as well. However, the status of the dimmer is not getting reflected correctly. Currently checking what is going on - not yet sure if it is HASS or the py library. FYI.

**Comment by tschamm** [comment]
I guess dimmer support is still missing in the lights platform, I have not looked into this.

**Comment by jumlu** [comment]
Found the issue - The current state was returned as PowerSwitchService.State and not as boolean. The HA part wasn't able to understand that value, so I changed it. New pull request is created.  Cheers.

**Pull request merged**
